### ISSUE TITLE
两个私有网络，可以通过中继器进行p2p连接建立通讯吗。

### ISSUE THREAD

**Issue by hshe** [HighValyrian/p2p-chat#2]

**Comment by waterbang** [comment]
你好，该项目还在开始阶段，你这个想法是可以实现的，就是指定某一个节点作为你所说的的中继器，转发两个私有网络的消息，但是可能会存在一些性能和安全问题，这需要进一步的讨论，但是目前没有该功能，期待您给出更有意思的想法！
